#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPC-Run
version:      0.79
version_from: lib/IPC/Run.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
