--- #YAML:1.0
name:               IPC-Run
version:            0.87
abstract:           system() and background procs w/ piping, redirs, ptys (Unix, Win32)
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
    Test::More:           0
requires:
    Test::More:  0.47
resources:
    bugtracker:  https://rt.cpan.org/NoAuth/Bugs.html?Dist=IPC-Run
    license:     http://dev.perl.org/licenses/
    repository:  http://svn.ali.as/cpan/trunk/IPC-Run
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    IO::Pty:  1.08
